#!/bin/bash

function start_wallpapers() {
    if [ "$2" == "right" ]
    then
        pos=1920+0
    else
        pos=0+0
    fi

    xwinwrap -g 1920x1080+$pos -ni -ov -s -b -nf -debug -- mpv $1 $3 -wid WID
}


LOCATION=0
#X, Y Offset
#This sets the distance of the window from the edge of the screen on the X and Y axis.
Y_AXIS=0
X_AXIS=0
WIDTH=10
# HEIGHT="'max-content'"
# height:$HEIGHT
STYLE="element{padding:4px4px4px0px;}listview{fixed-height:false;}"

# Rofi command to pipe into, can add any options here
rofi_command_add="-location $LOCATION -yoffset $Y_AXIS -xoffset $X_AXIS -theme-str window{width:"$WIDTH"em;}$STYLE"
rofi_command="rofi $rofi_command_add -dmenu $* -p"


function play() {
    monitor="$(echo -e "left\nright" | $rofi_command "󰍹" )"
    loop="$(echo -e "loop\nno_loop" | $rofi_command "󰍹" )"
    args=
    case $loop in
        "loop")
            args=--loop
            ;;
    esac
    url="$($rofi_command "URL" )"
    
    # current_monitor=$"(cat /tmp/__WM__CURRENT_MONITOR__)"

    if [ ! -z "$url" ]
    then
        start_wallpapers $url $monitor $args
    fi
}

function stop() {
    pkill xwinwrap
}


function show_menu() {
    options="play\nstop"

    chosen="$(echo -e "$options" | $rofi_command "" )"

    case $chosen in
        "play")
            play
            ;;
        "stop")
            stop
            ;;
        *)
            ;;
    esac
}


case $1 in
    "start")
        show_menu
        ;;
esac
