#!/bin/bash

function get_brightness() {
	echo $( light -G )
}

function send_notification() {
	brightness=$( get_brightness )
    brightness=$( printf "%.*f\n" 0 $brightness )
	dunstify -a "changebrightness" -u low -r "9993" -h int:value:"$brightness" -i "brightness-$1" "󰖨 Brightness: ${brightness}%" -t 2000
}

case $1 in
up)
    light -A 5
	send_notification $1
	;;
down)
    light -U 5
	send_notification $1
	;;
# mute)
# 	if $(light -G); then
#         light -I
# 		dunstify -a "changebrightness" -t 2000 -r 9993 -u low "󰖨 Unmuted"
# 	else
#         light -S 0
# 		dunstify -a "changebrightness" -t 2000 -r 9993 -u low "󰖨 Muted"
# 	fi
# 	;;
get)
	brightness=$( get_brightness )
	brightness=$( printf "%.*f\n" 0 $brightness )
	echo "${brightness}"
	;;
esac