unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g focus-events on
set -g renumber-windows on
set -g set-clipboard on
setw -g pane-base-index 1

set -g status-position top
set -g status-interval 5
set -g status-left-length 40
set -g status-left "#[bold] #S "
set -g status-right "#{?client_prefix,#[reverse] PREFIX #[default],} %H:%M "
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[reverse,bold]#I:#W#[default] "

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

bind-key r source-file "$HOME/.config/tmux/base.conf" \; display-message "Reloaded ~/.config/tmux/base.conf"
bind-key s choose-tree -sZ
bind-key S command-prompt -p "New or attach session:" "new-session -A -s '%%'"

bind-key -n M-t new-window -c "#{pane_current_path}"
bind-key -n M-w confirm-before -p "Kill window #W? (y/n)" kill-window

bind-key -n M-a select-window -t:4
bind-key -n M-s select-window -t:3
bind-key -n M-d select-window -t:2
bind-key -n M-f select-window -t:1

bind-key -n M-v copy-mode
bind-key -T copy-mode-vi Escape if -F "#{selection_active}" "send-keys -X clear-selection" "send-keys -X cancel"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "copy-to-clipboard"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "copy-to-clipboard"
