unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

set -g focus-events on
set -g renumber-windows on
set -g set-clipboard on
setw -g pane-base-index 1

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

set -g status-position top
set -g status-interval 5

set -g focus-events on
set -g status-style bg=default
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 99
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 99
set -g status-justify absolute-centre

setw -g window-status-style "bg=default,fg=default"
setw -g window-status-current-style "bg=default,fg=default,bold"
setw -g window-status-format "#[fg=#909090,bg=default] #W #[default]"
setw -g window-status-current-format "#[fg=#282c34,bg=#61afef,bold] #W #[default]"

set-hook -g after-new-session 'run-shell "
session=\"#{session_name}\"

case \"\$session\" in
  popup-*)
    tmux set-option -t "\$session" status off
    exit 0
    ;;
esac

dir=\$(tmux display-message -p -t \"\$session:1.1\" \"#{pane_current_path}\")

tmux new-window -d -t \"\$session:\" -c \"\$dir\"
tmux new-window -d -t \"\$session:\" -c \"\$dir\"
tmux new-window -d -t \"\$session:\" -c \"\$dir\"
tmux select-window -t \"\$session:1\"
"'

bind-key r source-file "$HOME/.config/tmux/base.conf" \; display-message "Reloaded ~/.config/tmux/base.conf"
bind-key s display-popup -E -w 90% -h 80% "tmux-project-session --pick"
bind-key S command-prompt -p "New or attach session:" "new-session -A -s '%%'"
bind-key v split-window -h -c "#{pane_current_path}"
bind-key h split-window -v -c "#{pane_current_path}"

bind-key -n M-t run-shell '
session="$(tmux display-message -p "#{session_name}")"
dir="$(tmux display-message -p "#{pane_current_path}")"

case "$session" in
  popup-*)
    tmux detach-client
    ;;
  *)
    tmux display-popup \
      -w 85% \
      -h 85% \
      -d "$dir" \
      -E "tmux new-session -A -s popup-$session -c \"$dir\""
    ;;
esac
'

bind-key -n M-a select-window -t:4
bind-key -n M-s select-window -t:3
bind-key -n M-d select-window -t:2
bind-key -n M-f select-window -t:1

bind-key -n M-v copy-mode
bind-key -T copy-mode-vi Escape if -F "#{selection_active}" "send-keys -X clear-selection" "send-keys -X cancel"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "copy-to-clipboard"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "copy-to-clipboard"
