#!/bin/bash

function getDeviceByName() {
    case $1 in
        touchpad)
            echo "Synaptics TM3276-022"
           	;;
        touchscreen)
            echo "ELAN Touchscreen"
           	;;
    esac
}

function toggleDeviceStatus() {
    DeviceName=$1
    read TPdevice <<< $( xinput | sed -nre "/${DeviceName}/s/.*id=([0-9]*).*/\1/p" )
    state=$( xinput list-props "$TPdevice" | grep "Device Enabled" | grep -o "[01]$" )

    if [ "$state" -eq '1' ];then
        xinput --disable "$TPdevice"
    else
        xinput --enable "$TPdevice"
    fi
}

for var in "$@"
do
    DeviceName=$(getDeviceByName "$var")
    toggleDeviceStatus $DeviceName
done
