# Use Hyprland's native CTM backend when running under Hyprland.
backend = "auto"
transition_mode = "geo"

smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

night_temp = 3300
day_temp = 6500
night_gamma = 90
day_gamma = 100
update_interval = "auto"

# Castelló de la Plana, Spain
latitude = 39.983333
longitude = -0.033333
