#!/bin/bash

intern="eDP-1"
extern="HDMI-2"

function configure_extern_monitor() {
    xrandr --output "$extern" --set audio force-dvi --mode 1920x1080
}

function configure_extern_monitor_location() {
    xrandr --output "$intern" --auto --output "$extern" $1 "$intern"
}

function disconnect_extern_monitor() {
    xrandr --output "$extern" --off --output "$intern" --auto
}

function disconnect_main_monitor() {
    xrandr --output "$intern" --off --output "$extern" --auto
}

function set_primary_monitor() {
    echo $1 > /tmp/__WM__CURRENT_MONITOR__
    xrandr --output $1 --primary
}

LOCATION=0
#X, Y Offset
#This sets the distance of the window from the edge of the screen on the X and Y axis.
Y_AXIS=0
X_AXIS=0
WIDTH=10
# HEIGHT="'max-content'"
# height:$HEIGHT
STYLE="element{padding:4px4px4px0px;}listview{fixed-height:false;}"

# Rofi command to pipe into, can add any options here
rofi_command_add="-location $LOCATION -yoffset $Y_AXIS -xoffset $X_AXIS -theme-str window{width:"$WIDTH"em;}$STYLE"
rofi_command="rofi $rofi_command_add -dmenu $* -p"


function chose_primary () {
    case $1 in
        $intern)
            set_primary_monitor $intern
            ;;
        $extern)
            set_primary_monitor $extern
            ;;
        *)
            ;;
    esac
}

function show_menu_primary() {
    options="$intern\n$extern"

    chosen="$(echo -e "$options" | $rofi_command "󰍹" )"

    chose_primary $chosen
}



function chose_location () {
    case $1 in
        "disconnect")
            disconnect_extern_monitor
            ;;
        "extend_left")
            configure_extern_monitor && configure_extern_monitor_location --left-of
            ;;
        "extend_right")
            configure_extern_monitor && configure_extern_monitor_location --right-of
            ;;
        "extend_top")
            configure_extern_monitor && configure_extern_monitor_location --above
            ;;
        "extend_bottom")
            configure_extern_monitor && configure_extern_monitor_location --below
            ;;
        "only_extend")
            disconnect_main_monitor
            ;;
        "duplicate")
            configure_extern_monitor && configure_extern_monitor_location --same-as
            ;;
        *)
            ;;
    esac
}

function show_menu_location() {
    options="disconnect\nextend_left\nextend_right\nextend_top\nextend_bottom\nonly_extend\nduplicate"

    chosen="$(echo -e "$options" | $rofi_command "󰍹" )"

    chose_location $chosen
}



function chose_menu () {
    case $1 in
        "Location_menu")
            show_menu_location
            ;;
        "Priority_menu")
            show_menu_primary
            ;;
        *)
            ;;
    esac
}

function show_menu() {
    options="Location_menu\nPriority_menu"

    chosen="$(echo -e "$options" | $rofi_command "󰍹" )"

    chose_menu $chosen
}



case $1 in
    "menu")
        show_menu
        ;;
    *)
        chose_location $1
        chose_primary $2
        ;;
esac
