#!/usr/bin/env bash

function get_brightness() {
  current=$(brightnessctl g)
  max=$(brightnessctl m)
  echo $((100 * current / max))
}

function send_notification() {
  brightness=$(get_brightness)
  brightness=$(printf "%.*f\n" 0 "$brightness")
  notify-send -a "changebrightness" -u low -h string:x-canonical-private-synchronous:brightness -h int:value:"$brightness" -i "brightness-$1" -t 2000 "󰖨 Brightness: ${brightness}%"
}

case $1 in
up)
  brightnessctl s 10%+
  send_notification "$1"
  ;;
down)
  brightnessctl s 10%-
  send_notification "$1"
  ;;
get)
  brightness=$(get_brightness)
  brightness=$(printf "%.*f\n" 0 "$brightness")
  echo "${brightness}"
  ;;
esac
